In [1]:
import os
import shutil

import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text as text
from official.nlp import optimization  # to create AdamW optimizer
from keras.callbacks import ModelCheckpoint
from keras.models import load_model

import matplotlib.pyplot as plt
import scipy.io
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler

from sklearn.manifold import TSNE
import seaborn as sns

import pandas as pd
import xlsxwriter
import numpy as np

tf.get_logger().setLevel('ERROR')

print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

Num GPUs Available:  1


In [4]:
the_bmatt_file = scipy.io.loadmat('binaryAtt_splits_AWA2.mat')
the_mat_file = scipy.io.loadmat('att_splits_AWA2.mat')
print(the_bmatt_file.keys())
print('')
print(the_mat_file.keys())

dict_keys(['__header__', '__version__', '__globals__', 'allclasses_names', 'att', 'test_seen_loc', 'test_unseen_loc', 'train_loc', 'trainval_loc', 'val_loc'])

dict_keys(['__header__', '__version__', '__globals__', 'allclasses_names', 'att', 'original_att', 'test_seen_loc', 'test_unseen_loc', 'train_loc', 'trainval_loc', 'val_loc'])


In [5]:
the_mat_file['train_loc']

array([[21483],
       [11453],
       [21449],
       ...,
       [19616],
       [10389],
       [ 5161]], dtype=uint16)

In [6]:
the_bmatt_file['train_loc']

array([[    1],
       [    2],
       [    3],
       ...,
       [37320],
       [37321],
       [37322]], dtype=uint16)

In [7]:
the_mat_file['att'] = the_bmatt_file['att']
the_mat_file['att']

array([[0, 1, 1, ..., 1, 1, 0],
       [0, 0, 1, ..., 1, 1, 1],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 1, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 1]], dtype=uint8)

In [8]:
scipy.io.savemat('binaryAtt_edited.mat', the_mat_file)